### ISSUE TITLE
[Bug] Trench STILL not working (1.13.2)

### ISSUE THREAD

**Issue by CaptainAmpersand** [GC-spigot/AdvancedEnchantments#244]
I opened a report, which was closed a while ago (And can't be re-opened #225 ) and it was said to be "Fixed"

I responded stating that it wasn't, however it appears to still be "Closed." So, new report!
PaperSpigot 1.13.2-469
AE Version 5.0.5
Worldedit 7.0.0-beta-03
Worldguard 7.0.0-snapshot;1761

Error:
```[00:03:43] [Server thread/WARN]: [AdvancedEnchantments] Task #17593 for AdvancedEnchantments v5.0.5 generated an exception
java.lang.NoSuchMethodError: com.sk89q.worldguard.bukkit.WorldGuardPlugin.canBuild(Lorg/bukkit/entity/Player;Lorg/bukkit/Location;)Z
	at n3kas.ae.hooks.b.a(b.java:18) ~[?:?]
	at n3kas.ae.effectsreader.e.f(e.java:951) ~[?:?]
	at n3kas.ae.effectsreader.e.a(e.java:98) ~[?:?]
	at n3kas.ae.enchanthandler.d$a.run(d$a.java:208) ~[?:?]
	at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftTask.run(CraftTask.java:82) ~[patched_1.13.2.jar:git-Paper-474]
	at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:448) ~[patched_1.13.2.jar:git-Paper-474]
	at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:1008) ~[patched_1.13.2.jar:git-Paper-474]
	at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:439) ~[patched_1.13.2.jar:git-Paper-474]
	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:943) ~[patched_1.13.2.jar:git-Paper-474]
	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:841) ~[patched_1.13.2.jar:git-Paper-474]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]
[00:03:44] [Server thread/WARN]: [AdvancedEnchantments] Task #17717 for AdvancedEnchantments v5.0.5 generated an exception
java.lang.NoSuchMethodError: com.sk89q.worldguard.bukkit.WorldGuardPlugin.canBuild(Lorg/bukkit/entity/Player;Lorg/bukkit/Location;)Z
	at n3kas.ae.hooks.b.a(b.java:18) ~[?:?]
	at n3kas.ae.effectsreader.e.f(e.java:951) ~[?:?]
	at n3kas.ae.effectsreader.e.a(e.java:98) ~[?:?]
	at n3kas.ae.enchanthandler.d$a.run(d$a.java:208) ~[?:?]
	at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftTask.run(CraftTask.java:82) ~[patched_1.13.2.jar:git-Paper-474]
	at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:448) ~[patched_1.13.2.jar:git-Paper-474]
	at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:1008) ~[patched_1.13.2.jar:git-Paper-474]
	at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:439) ~[patched_1.13.2.jar:git-Paper-474]
	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:943) ~[patched_1.13.2.jar:git-Paper-474]
	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:841) ~[patched_1.13.2.jar:git-Paper-474]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]
```

Good news is that Repeating now works on 1.13, I see you're doing great work, just continuing to try and give you more feedback as time progresses :)

**Comment by GC-spigot** [comment]
I can't reproduce this but I will attempt another fix. Thank you for reporting.
