### ISSUE TITLE
Some Enchants not working. Faction Hook issue

### ISSUE THREAD

**Issue by marasman12** [GC-spigot/AdvancedEnchantments#3486]
### Describe the bug

Examples of water walker and lava walker not working. Only works on versions 9.0.0b54. These are the only reported enchantments not working for me. Console is spammed with the following...

[16:14:40] [Server thread/ERROR]: Could not pass event PlayerMoveEvent to AdvancedEnchantments v9.2.13
java.lang.NoSuchMethodError: 'com.massivecraft.factions.perms.Relation com.massivecraft.factions.FPlayer.getRelationToLocation()'
	at net.advancedplugins.ae.impl.utils.hooks.plugins.FactionsUUIDHook.getRelationOfLand(FactionsUUIDHook.java:30) ~[AdvancedEnchantments-9.2.13.jar:?]
	at net.advancedplugins.ae.impl.effects.effects.effects.internal.LavaWalkerEffect.checkAndSet(LavaWalkerEffect.java:97) ~[AdvancedEnchantments-9.2.13.jar:?]
	at net.advancedplugins.ae.impl.effects.effects.effects.internal.LavaWalkerEffect.scanBlocks(LavaWalkerEffect.java:92) ~[AdvancedEnchantments-9.2.13.jar:?]
	at net.advancedplugins.ae.impl.effects.effects.effects.internal.LavaWalkerEffect.onMove(LavaWalkerEffect.java:61) ~[AdvancedEnchantments-9.2.13.jar:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor1113.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:75) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:git-Paper-379]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:669) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.handleMovePlayer(ServerGamePacketListenerImpl.java:1505) ~[?:?]
	at net.minecraft.network.protocol.game.ServerboundMovePlayerPacket.handle(ServerboundMovePlayerPacket.java:29) ~[?:?]
	at net.minecraft.network.protocol.game.ServerboundMovePlayerPacket$Pos.handle(ServerboundMovePlayerPacket.java:66) ~[?:?]
	at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$1(PacketUtils.java:51) ~[?:?]
	at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.18.2.jar:git-Paper-379]
	at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
	at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1400) ~[paper-1.18.2.jar:git-Paper-379]
	at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:188) ~[paper-1.18.2.jar:git-Paper-379]
	at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
	at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1377) ~[paper-1.18.2.jar:git-Paper-379]
	at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1370) ~[paper-1.18.2.jar:git-Paper-379]
	at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
	at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1348) ~[paper-1.18.2.jar:git-Paper-379]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1230) ~[paper-1.18.2.jar:git-Paper-379]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316) ~[paper-1.18.2.jar:git-Paper-379]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]

### How to reproduce

Occurs when the server is runnning, No enchantments or players are needed to create these error codes. Looks like a Faction Hook but not sure if that would be causing some enchants to not work. Plugin is Saber Factions

### "/ae plinfo" link

https://paste.md-5.net/usupucalul

### Server Log

https://mcpaste.io/c18ff364d376988c

**Comment by BadgersMC** [comment]
Im having a similar issue with Trench, and all of the Planter enchantments (carrotplanter, wheatplanter, potato, exc..)
console is spamming with Faction hook errors


[Replanter.txt](https://github.com/GC-spigot/AdvancedEnchantments/files/12163741/Replanter.txt)

[Trench Error.txt](https://github.com/GC-spigot/AdvancedEnchantments/files/12163742/Trench.Error.txt)

Plugin List: https://paste.md-5.net/iluwepebis

Log: https://mcpaste.io/dadf6a997e0ee23c
