### ISSUE TITLE
Plugin does not work in PaperSpigot 1.8.8

### ISSUE THREAD

**Issue by agus-marmor** [GC-spigot/AdvancedEnchantments#2562]
### Describe the bug

[01:14:02 ERROR]: Error occurred while enabling AdvancedEnchantments v8.7.27 (Is it up to date?)
java.lang.NoClassDefFoundError: org/bukkit/inventory/ItemFlag
        at net.advancedplugins.ae.enchanthandler.enchantments.AdvancedGroup.<init>(AdvancedGroup.java:125) ~[?:?]
        at net.advancedplugins.ae.enchanthandler.enchantments.AdvancedGroup.lambda$loadGroups$0(AdvancedGroup.java:77) ~[?:?]
        at java.util.ArrayList.forEach(ArrayList.java:1259) ~[?:1.8.0_312]
        at net.advancedplugins.ae.enchanthandler.enchantments.AdvancedGroup.loadGroups(AdvancedGroup.java:75) ~[?:?]
        at net.advancedplugins.ae.Core.onEnable(Core.java:352) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:316) ~[server.jar:1.0]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:332) [server.jar:1.0]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:411) [server.jar:1.0]
        at org.bukkit.craftbukkit.v1_7_R4.CraftServer.loadPlugin(CraftServer.java:466) [server.jar:1.0]
        at org.bukkit.craftbukkit.v1_7_R4.CraftServer.enablePlugins(CraftServer.java:385) [server.jar:1.0]
        at net.minecraft.server.v1_7_R4.MinecraftServer.n(MinecraftServer.java:344) [server.jar:1.0]
        at net.minecraft.server.v1_7_R4.MinecraftServer.g(MinecraftServer.java:318) [server.jar:1.0]
        at net.minecraft.server.v1_7_R4.MinecraftServer.a(MinecraftServer.java:278) [server.jar:1.0]
        at net.minecraft.server.v1_7_R4.DedicatedServer.init(DedicatedServer.java:230) [server.jar:1.0]
        at net.minecraft.server.v1_7_R4.MinecraftServer.run(MinecraftServer.java:485) [server.jar:1.0]
        at net.minecraft.server.v1_7_R4.ThreadServerApplication.run(SourceFile:628) [server.jar:1.0]
Caused by: java.lang.ClassNotFoundException: org.bukkit.inventory.ItemFlag
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:90) ~[server.jar:1.0]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:85) ~[server.jar:1.0]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:418) ~[?:1.8.0_312]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:351) ~[?:1.8.0_312]
        ... 16 more

### How to reproduce

Just use spigotpaper for 1.8 and use the lastest version of the plugin

### Screenshots / Videos

![image](https://user-images.githubusercontent.com/56454462/147714236-89d84e93-0e6e-4f33-ab19-544b33e004bc.png)

### "/ae plinfo" link

I cant, it just responds "/AdvancedEnchantments"

### Server Log

https://mcpaste.io/6e38ea892ac92fb7
